-- Generated by convert_png_to_tga.py; shipped with the preview textures.
-- Keys select images; filename labels supply titles, not hyperlink text.
RQE = RQE or {}
RQE.ObjectPreviewCatalog = {
	["187900"] = { file = "187900 - Fizzcrank Spare Parts.tga", name = "Fizzcrank Spare Parts" },
	["187984"] = { file = "187984 - West Point Station Valve.tga", name = "West Point Station Valve" },
	["187985"] = { file = "187985 - North Point Station Valve.tga", name = "North Point Station Valve" },
	["187986"] = { file = "187986 - Mid Point Station Valve.tga", name = "Mid Point Station Valve" },
	["188109"] = { file = "188109 - South Point Station Valve.tga", name = "South Point Station Valve" },
}
